export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

//SIGN UP
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const SIGN_UP_SUCCESS= "SIGN_UP_SUCCESS";

//ADD GIST
export const ADD_GIST_REQUEST= "ADD_GIST_REQUEST";
export const ADD_GIST_ERROR= "ADD_GIST_ERROR";
export const ADD_GIST_SUCCESS= "ADD_GIST_SUCCESS";


